/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Account;
import model.AccountDirectory;
import model.Utils;

/**
 *
 * @author vishnupaduchuri
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    private AccountDirectory accountDirectory;
    private JPanel UserProcessContainer;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(JPanel UserProcessContainer, AccountDirectory accountDirectory) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.accountDirectory = accountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRoutingNumber = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblCreateAccountTitle = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        txtRoutingNumber = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRoutingNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRoutingNumber.setText("Routing Number:");
        lblRoutingNumber.setToolTipText("");
        add(lblRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 103, 101, -1));

        lblAccountNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAccountNumber.setText("Account Number:");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 144, -1, -1));

        lblBankName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBankName.setText("Bank Name:");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 185, 101, -1));

        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBalance.setText("Balance:");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 226, 101, -1));

        lblCreateAccountTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCreateAccountTitle.setText("Create Account");
        add(lblCreateAccountTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 141, 200, -1));
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 100, 200, -1));

        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 182, 200, -1));
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 223, 200, -1));

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 273, 200, 40));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        String routingNumber = txtRoutingNumber.getText();
        String accountNumber = txtAccountNumber.getText();
        String bankName = txtBankName.getText();
        String balanceText = txtBalance.getText();
        
        if(routingNumber.isBlank() || accountNumber.isBlank() || bankName.isBlank() || balanceText.isBlank()) {
            JOptionPane.showMessageDialog(this, "The Fields can't be empty");
            return;
        }
        
        if(!Utils.isValidRoutingNumber(routingNumber)) {
            JOptionPane.showMessageDialog(null, "Invalid!! Routing Number has to be 9 digits !");
            return;
        }
        
        if(!Utils.isValidAccountNumber(accountNumber)) {
            JOptionPane.showMessageDialog(null, "Invalid!! Account Number has to be between 10 to 12 digits !");
            return;
        }
        
        if(!Utils.isValidBankName(bankName)) {
            JOptionPane.showMessageDialog(null, "Bank Name is Invalid!");
            return;
        }
        
        if(!Utils.isValidBalance(balanceText)) {
            JOptionPane.showMessageDialog(null, "Balance has to be numeric!");
            return;
        }
        
        int balance = Integer.parseInt(balanceText);

        Account account = accountDirectory.addAccount();
        account.setRoutingNumber(routingNumber);
        account.setAccountNumber(accountNumber);
        account.setBankName(bankName);
        account.setBalance(balance);
        
        JOptionPane.showMessageDialog(null, "Account Created Successfully!");
        txtRoutingNumber.setText("");
        txtAccountNumber.setText("");
        txtBankName.setText("");
        txtBalance.setText("");
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCreateAccountTitle;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
